version: '3.8'

services:
  db-postgres:
    container_name: database_postgres
    image: postgres:latest

    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=users
      
    
    ports:
      - 5432:5432